version: '3.9'

services:
  db:
    image: mysql:8
    container_name: debateia-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-password
      - MYSQL_DATABASE=human_traits
    networks:
      - lab-network
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debateia-app
    ports:
      - "8081:8081"
    networks:
      - lab-network
    depends_on:
      db: 
        condition: service_started
    restart: always

networks:
  lab-network:
    driver: bridge