#Base de Dades creada amb docker, com utilizar-la

#    1. Instalar Docker Desktop
#    2. A nes terminal executar 'docker-compose up -d' aixo crea sa bd
#    3. Despres executar SpringBoot a nes DemoApplication

#    Se pot accedir a nes phpMyAdmin per mirar si ses taules de sa bd s'han creat i després se pot utilizar swagger per mirar si funciona.
#    Hi ha un usuari predefinit que se crea quan s'executa es docker-compose


version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: jaumesitos-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jaumesitos
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: jaumesitos-phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: app
      PMA_PASSWORD: app

volumes:
  mysql_data: