version: '3.9'

services:
  db:
    image: mysql:8
    container_name: debateia-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-password
      - MYSQL_DATABASE=human_traits
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    restart: always
