openapi: 3.0.0
info:
  title: Gironeta Server API
  description: This file defines the communication contract between the AI league application front-end and the back-end service.
  version: 1.0.0
paths:
  /api/v0/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserDto'
      responses:
        '200':
          description: User created successfully
        '409':
          description: Conflict
        '500':
          description: Internal server error
  /api/v0/auth/login:
    post:
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserDto'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error
  /api/v0/bot:
    post:
      summary: Create a new bot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BotDto'
      responses:
        '201':
          description: Bot created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BotResponseDto'
        '400':
          description: Bad request
    get:
      summary: Get all bots
      parameters:
        - in: query
          name: owner
          schema:
            type: integer
          description: User ID of the bot owner
      responses:
        '200':
          description: List of bots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BotSummaryDto'
        '404':
          description: Not found
  /api/v0/bot/{botId}:
    get:
      summary: Get a bot by ID
      parameters:
        - in: path
          name: botId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Bot details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BotResponseDto'
        '404':
          description: Not found
    put:
      summary: Update a bot by ID
      parameters:
        - in: path
          name: botId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BotResponseDto'
      responses:
        '200':
          description: Bot updated successfully
        '400':
          description: Bad request
        '404':
          description: Not found
  /api/v0/league:
    post:
      summary: Create a new league
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LeagueDto'
      responses:
        '201':
          description: League created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeagueResponseDto'
        '400':
          description: Bad request
    get:
      summary: Get all leagues
      parameters:
        - in: query
          name: owner
          schema:
            type: integer
          description: User ID of the league owner
      responses:
        '200':
          description: List of leagues
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LeagueResponseDto'
        '404':
          description: Not found
  /api/v0/league/{id}:
    get:
      summary: Get a league by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: League details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeagueResponseDto'
        '404':
          description: Not found
    put:
      summary: Update a league by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LeagueDto'
      responses:
        '200':
          description: League updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeagueResponseDto'
        '400':
          description: Bad request
        '404':
          description: Not found
  /api/v0/league/{id}/bot:
    post:
      summary: Register a bot to a league
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                botId:
                  type: integer
      responses:
        '201':
          description: Bot registered successfully
        '400':
          description: Bad request
        '404':
          description: Not found
  /api/v0/league/{leagueId}:
    delete:
      summary: Delete a league by ID
      parameters:
        - in: path
          name: leagueId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: League deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeagueResponseDto'
        '404':
          description: Not found
  /api/v0/league/{leagueId}/start:
    post:
      summary: Start a league
      parameters:
        - in: path
          name: leagueId
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: League started successfully
        '400':
          description: Bad request
        '404':
          description: Not found
  /api/v0/league/{leagueId}/leaderboard:
    get:
      summary: Get the leaderboard of a league
      parameters:
        - in: path
          name: leagueId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Leaderboard details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ParticipationResponseDto'
        '404':
          description: Not found
  /api/v0/league/{leagueId}/match:
    get:
      summary: Get matches of a league
      parameters:
        - in: path
          name: leagueId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Matches details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MatchResponseDTO'
        '404':
          description: Not found
  /api/v0/match/{matchId}/message:
    get:
      summary: Get messages of a match
      parameters:
        - in: path
          name: matchId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Messages details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MessageResponseDTO'
        '404':
          description: Not found
components:
  schemas:
    RegisterUserDto:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    LoginUserDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UserResponseDTO:
      type: object
      properties:
        token:
          type: string
        expiresIn:
          type: string
        user:
          type: string
        userId:
          type: integer
    BotDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        urlImagen:
          type: string
        endpoint:
          type: string
    BotResponseDto:
      type: object
      properties:
        botId:
          type: integer
        name:
          type: string
        description:
          type: string
        urlImagen:
          type: string
        nWins:
          type: integer
        nLosses:
          type: integer
        nDraws:
          type: integer
    BotSummaryDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        id:
          type: integer
    LeagueDto:
      type: object
      properties:
        name:
          type: string
        urlImagen:
          type: string
        rounds:
          type: integer
        matchTime:
          type: integer
        bots:
          type: array
          items:
            type: integer
    LeagueResponseDto:
      type: object
      properties:
        leagueId:
          type: integer
        state:
          type: string
        name:
          type: string
        urlImagen:
          type: string
        user:
          type: integer
        rounds:
          type: integer
        matchTime:
          type: integer
        bots:
          type: array
          items:
            type: integer
    ParticipationResponseDto:
      type: object
      properties:
        botId:
          type: integer
        name:
          type: string
        points:
          type: integer
        position:
          type: integer
        nwins:
          type: integer
        ndraws:
          type: integer
        nlosses:
          type: integer
    MatchResponseDTO:
      type: object
      properties:
        matchId:
          type: integer
        state:
          type: string
        result:
          type: integer
        fighters:
            type: array
            items:
              type: integer
        roundNumber:
          type: integer
    MessageResponseDTO:
      type: object
      properties:
        text:
          type: string
        botId:
          type: integer
        time:
          type: string
          format: date-time