spring:
  profiles:
    active: devel

---

spring:
  config:
    activate:
      on-profile: devel

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/jaumesitos
    username: app
    password: app
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:db/taules.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
