spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/lab_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: lab_user
    password: lab_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  messages:
    use-code-as-default-message: true
management:
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:80, http://localhost:8080, http://localhost:8081"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
client:
  url: "http://localhost:80"
logging:
  level:
    web: DEBUG
