spring:
  profiles:
    active: "dev"
  security:
    login:
      success-url: "http://localhost/"
  messages:
    fallback-to-system-locale: false
server:
  port: 8081
  servlet:
    encoding:
      charset: "UTF-8"
  error:
    include-stacktrace: never
    include-message: always
jwt:
  prefix: "Bearer "
  authentication:
    secret: '>pNHz358mC@f}>~@Une1^9z5"up!Z)IDKwbyRwnZrTyXahAletzmYv3l4U9gTujkmo'
    duration: 14
    temporal-unit: days
  verification:
    secret: '9W9|Z.9rvDZ1?)r]cV$[)d!OE/0COvB?*MOY@h2"293TF]uY$;8xyyfOgP'
    duration: 5
    temporal-unit: minutes